version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: zaian
      POSTGRES_PASSWORD: zaian123
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
